version: "3.8"

services:
  tejas:
    build: .
    container_name: tejas
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    networks:
      - tejas_net

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5555:5678"
    volumes:
      - "C:/Users/shrav/DEV_WORKSPACE/06_n8n_automation/docker_setup/n8n:/home/node/.n8n"
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_TEMPLATES_ENABLED=true
      - N8N_EDITOR_BASE_URL=https://interlacustrine-candace-pleasedly.ngrok-free.dev
      - WEBHOOK_URL=https://interlacustrine-candace-pleasedly.ngrok-free.dev
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    depends_on:
      - tejas
    networks:
      - tejas_net

  frontend:
    image: nginx:alpine
    container_name: tejas_frontend
    ports:
      - "8080:80"
    volumes:
      - "C:/Users/shrav/DEV_WORKSPACE/06_n8n_automation/docker_setup/n8n/static:/usr/share/nginx/html:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - tejas
      - n8n
    networks:
      - tejas_net

networks:
  tejas_net:
    driver: bridge